### PR TITLE
answers text updated

### PR DESCRIPTION
**Pull request by varun1309**

### CODE REVIEW

**Review by abhinab22mohanty — APPROVED** [review]
Answers Look Good 
Suggestion: Two Questions missing

**Comment by abhinab22mohanty** [comment]
Suggestion: Two Questions Missing but Answers look good

**Comment by varun1309** [comment]
Line 1 and 2 might be hidden in the file comparison page if that is what you mean.

**Comment by abhinab22mohanty** [comment]
Yes, it's fine no issues raised.

**Pull request merged**
